name: Slack Bot

# 定期実行スケジュール
on:
  schedule:
    # 平日の日本時間AM8:00に実行 (UTCでは0:00)
    - cron: '0 0 * * 1-5' # GitHub ActionsのcronはUTCで指定
  workflow_dispatch: # 手動で実行できるようにする

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: チェックアウト
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 使用するNode.jsのバージョン

      # 依存関係をインストール
      - name: 依存関係のインストール
        run: npm install

      # Slackメッセージ送信スクリプトを実行
      - name: メッセージ送信
        run: npm start
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
